### ISSUE TITLE
Post-Newtonian formulation?

### ISSUE THREAD

**Issue by asmfishcc** [rodyo/FEX-RKN1210#1]
Hi, would it be possible to add relativistic corrections for this integrator? Thanks.

**Comment by rodyo** [comment]
No. 

First, this is not up to a numerical ODE integrator, but up to the ODE defining the problem. 

Second, post-Newtonian formulation (without simplifications or linearisations) involves the factor λ = 𝑣²/𝑐², with 𝑣 the instantaneous speed of the body and 𝑐 the speed of light. Since any RKN scheme explicitly assumes the ODE under evaluation does not involve the first derivative, this integrator cannot deal with any effect involving the body's speed. That includes things like air drag, Poynting/Robertson, and thus also relativistic effects.

**Comment by rodyo** [comment]
(unless you can provide also 3ʳᵈ derivatives; then 𝑍 = [𝑟 𝑣]  →  d²𝑍/d𝑡² = [𝑎  d³𝑟/d𝑡³] can be used to do the integration. But third derivatives are quite uncommon in celestial mechanics, and not always easily computed for many perturbative forces. At least for relativistic corrections, I've never done it)
